### ISSUE TITLE
Fix tab spacing

### ISSUE THREAD

**Issue by ceckenrode** [gibbous/Basic-Portfolio#1]
in sublime set your tab spacing to 2. Sublime's default is 4, but the most widely agreed upon spacing is 2.

You can do this like so

In sublime go to 

Preferences > Settings - User > 

Inside here, delete everything and replace it with 

}
  "tab_size": 2,
}

save, and restart sublime. going forward your tab sizes with be 2 spaces. This just makes code easier to read and maintain

**Comment by gibbous** [comment]
updated, thanks!
