### ISSUE TITLE
portfolio.html footer

### ISSUE THREAD

**Issue by ceckenrode** [gibbous/Basic-Portfolio#3]
footer here isn't all the way at the bottom of the page. Looks like this page is longer than the others. At this stage I'd suggest making one base css file for all the styles that are going to be exactly the same from one page to another. Then making smaller css files for more specific things on other pages

**Comment by gibbous** [comment]
having trouble with the footer overlapping the content. it affects all the pages but is only apparent on this one. back to the drawing board

**Comment by gibbous** [comment]
made the container on the portfolio page taller to push the footer down.
